name: CI

on:
  push:  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4 
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: 3.11

    - name: View actual folder structure
      run: |
        echo "=== Where am I? ==="
        pwd
        echo "=== What files are here? ==="
        ls -R

    - name: Install dependencies
      working-directory: ./github-actions-lab1-q1
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
